---
queue_rules:
  - name: default
    conditions:
      - check-success~=Build docs
      - check-success~=Build package
      - check-success~=docs/readthedocs.org

pull_request_rules:
  - name: default
    conditions:
      - label=ready-to-merge
      - '#approved-reviews-by>=1'
      - status-success~=Build docs
      - status-success~=Build package
      - status-success~=docs/readthedocs.org
    actions:
      queue:
        method: rebase
        name: default
        rebase_fallback: none
