# .readthedocs.yml
# Read the Docs configuration file

# Details
# - https://docs.readthedocs.io/en/stable/config-file/v2.html

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.14"
  apt_packages:
    - plantuml

  jobs:

    # Install `uv`.
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv

    # Install dependencies using `uv`.
    install:
      - uv pip install --upgrade -r docs/requirements.txt

    # Bundle assets, because `pip install --editable=.` does not do it.
    pre_build:
      - make bundle-develop
      - cd docs; make bundle-assets

    # Invoke the build also using `uv`.
    build:
      html:
        - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
